### ISSUE TITLE
Question - ledger-arweave address and imported passphrase address 

### ISSUE THREAD

**Issue by zhaomengru2015** [jfbeats/ArweaveWebWallet#8]
Hey! I recently venture into arweave blockchain and I've tried both [arconnect](https://www.arconnect.io/) and `arweave.app` (this poject) wallets, and I found that `arweave.app` already work in progress to support ledger hardware wallet and I really like it!

I know that `Ledger Hardware Wallet` support have not been officially released and I want to try this awesome feature in advance, so I follow the [ledger-arweave](https://github.com/Zondax/ledger-arweave) documentation and successfully installed the Arweave app on my ledger nanos device. 

Then I connect my ledger nanos device with [our wallet](https://arweave.app/) :

<img width="815" alt="ledger-address" src="https://user-images.githubusercontent.com/9380107/170140376-6db29244-d5dc-4019-95bb-14362b3ce276.png">

But when I import the same passphrase on our wallet, it generate a different address:

<img width="470" alt="passphrase address" src="https://user-images.githubusercontent.com/9380107/170140735-626bd1e7-44b9-4f01-bd20-bdbde5f14e19.png">

I know that `passphrase address` and `ledger address` are using different deterministic RSA keys, `passphrase address` generated by [human-crypto-keys](https://github.com/ipfs-shipyard/js-human-crypto-keys) , whereas `ledger address` generated by [ledger-arweave](https://github.com/Zondax/ledger-arweave).

Are there any specifications/standard to follow to generate  same deterministic RSA key from mnemonic?

**Comment by jfbeats** [comment]
Yes you are right, the derivation that ledger implemented is different from the commonly used javascript one. Currently, there is no specific standard to follow
